# Generated by Django 6.0.3 on 2026-04-05 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.IntegerField(null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                ("currency", models.CharField(default="USD", max_length=13)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
