# Generated by Django 6.0.3 on 2026-04-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="Invoice_number",
            new_name="invoice_number",
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("tenant", "invoice_number")},
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="Invoice",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
            ),
            preserve_default=False,
        ),
    ]
